### ISSUE TITLE
Take SerializationInclusion into consideration

### ISSUE THREAD

**Issue by natnan** [zapodot/jackson-databind-java-optional#2]
I have set my ObjectMapper to ignore null values using 

```java
objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
```

so it wouldn't generate unnecessary ```"myObject" = null```.

This module(which I'm using via dropwizard) ignores the inclusion setting and serializes null. I was wondering if it'd be possible for this module to not ignore it.

**Comment by natnan** [comment]
Hi @zapodot . Sorry, I've assumed I'd get email from github for your response, so didn't get back here to check (nor logged in github to check notifications). Then, totally forgot about it.

As I've said I'm using dropwizard, which adds bunch of modules to object mapper. I was able to isolate it to [afterburner module](https://github.com/FasterXML/jackson-module-afterburner). So if you add 
```objectMapper.registerModule(new AfterburnerModule())```
the test will fail.

I'm not sure whether it's as expected. I'll be digging more.

**Comment by zapodot** [comment]
The AfterBurner module seems to have caused problems for other modules as well. I will have a look at it to see if I can find a solution.

**Comment by zapodot** [comment]
@natnan : just added a new [test class](https://github.com/zapodot/jackson-databind-java-optional/blob/master/src/test/java/org/zapodot/jackson/java8/AfterBurnerInteroperabilityTest.java) that tests serialization/deserialization with AfterBurner enabled as well as the JsonInclude.Include.NON_NULL setting. Does your beans look different from the one I use in the test class? The best approach moving forward would be if you could provide a failing test or at least describe your use case in more detail (how you have defined your POJOs,  and  which version of Jackson you are using in your project).

**Comment by natnan** [comment]
@zapodot 
```java
@Test
  public void test_directly_object_mapper() throws IOException {
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.registerModule(new AfterburnerModule());
    objectMapper.registerModule(new JavaOptionalModule());
    objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);

    String jsonText = objectMapper.writeValueAsString(new CustomJsonObject());

    JsonNode json = objectMapper.readTree(jsonText);
    
    ...
    assertThat(json.has("optionalEmpty")).isFalse();
  }
...
@Data //lombok
    public class CustomJsonObject {
      private int integer = 5;
      private String nullString = null;
      private Optional<String> optionalEmpty = Optional.empty();
      private Optional<String> optionalString = Optional.of("optional string");
    }
```

By the way if I've just realized, if I move AfterburnerModule registration below JavaOptionalModule, the test passes. However, in your test, it's already below; so I guess that's not it.

Jackson 2.3.3
Now I realize I should have tested it with the latest version before taking it here :), sorry about that. I'll create a quick project with the latest version and let you know.

**Comment by natnan** [comment]
It fails the same way with the following gradle:
```
    compile 'com.fasterxml.jackson.core:jackson-core:2.4.3'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.3'
    compile 'com.fasterxml.jackson.core:jackson-datatype-jdk7:2.4.3'
    compile 'com.fasterxml.jackson.module:jackson-module-afterburner:2.4.3'
    compile 'org.zapodot:jackson-databind-java-optional:2.4.3'
```

**Comment by zapodot** [comment]
As the test I just added shows this will occur if you have standard JavaBean POJOs. In that case the getters will be used for serialization and if AfterBurner has been initialized before this module our writer will never run. Possible workarounds (apart from changing module load-order) is to annotate the fields with @JsonProperty as that will avoid the AfterBurner optimized property serializers from being invoked.

No other fix is posible at this time because I can not change the behaviour of the AfterBurner module..

Sorry for that :-(

**Comment by natnan** [comment]
I understand. Unfortunately I can't change the order but I can annotate the fields even though that's far from pretty. It's better than nothing though :).

I appreciate the time you've spent. Thank you very much.

**Comment by zapodot** [comment]
If you don't like the idea of adding @JsonProperty annotations to the POJOs, have a look at http://wiki.fasterxml.com/JacksonFeatureBuilderPattern
